// This file was generated by gir (https://github.com/gtk-rs/gir @ 7f5a2b5)
// from gir-files (https://github.com/gtk-rs/gir-files @ ???)
// DO NOT EDIT

/* For %z support in printf when using MinGW. */
#define _POSIX_C_SOURCE 200809L
#include <stdalign.h>
#include <stdio.h>
#include "manual.h"

int main() {
    printf("%zu\n%zu", sizeof(ABI_TYPE_NAME), alignof(ABI_TYPE_NAME));
    return 0;
}
